[project]
name = "oh-my-light"
version = "0.1.0"
description = "Home Assistant integration for Oh My Light"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "homeassistant>=2023.7.3",
]

[tool.ruff]
line-length = 120